<form name="iform" action="<?= BASE_URL . "/private/account/uploadpicture"?>" method="post" enctype="multipart/form-data">
    <input id="file" type="file" name="picture" onChange="window.parent.QHelpers.account.uploadPicture(this);" /><br>
    <span><?= $this->tr("Tipos de archivo permitidos: jpg, png, svg y gif.")?></span>
    <input type="hidden" value="" name="account_id" />
</form>

<script language="javascript">
    window.parent.QHelpers.account.addIframe(window);
</script>