<div>
    <span class="account-name"><?= strtoupper($this->account->name) ?></span>
    <span>$<?= $this->account->benefit ?></span>
    <?=$this->count?> transacciones
</div>
<a href="#" id="add-income" class="add-transaction" onclick="return false;">Adicionar ingresos</a>
<br>
<a href="#" id="add-expense" class="add-transaction" onclick="return false;">Adicionar egresos</a>
<div id="transactions-container">
    <?php foreach ($this->transactions as $transaction){
        $m = new Mustache_Engine;
    ?>
        <?= $m->render($this->render("mustache/transaction-row.phtml"), array(
            "id" => $transaction->id,
            "transactionUrl" => $this->createUrl("transaction", $transaction),
            "name" => $transaction->name,
            "timestampDate" => $transaction->date,
            "date" => Contabilidad_Utils_Dates::toDate($transaction->date),
            "value" => $transaction->value,
            "dateClass" => $transaction->date > time() ? "@" : "",
            "transactionType" => $transaction->id_transaction_type == 1 ? "income" : "expense"
        ));?>
    <?php }?>
</div>

<div id="transaction-row-tpl" class="template" style="display: none;">
    <?= $this->render("mustache/transaction-row.phtml") ?>
</div>

<div id="create-mini-transaction-form" style="display: none;">
    <?php echo $this->render('partials/createMiniTransactionForm.phtml'); ?>
    <span class="js-time" style="display: none;"><?= time() ?></span>
    <div class="response"></div>
</div>

<div id="create-transaction-form" style="display: none;">
    <?php echo $this->render('partials/createTransactionForm.phtml'); ?>
    <span class="js-time" style="display: none;"><?= time() ?></span>
    <div class="response"></div>
</div>

<script language="javascript">
    window.Contabilidad.account = <?= Zend_Json::encode($this->serializedAccount); ?>
</script>