<div>
    <?php $m = new Mustache_Engine; ?>
    <?= $m->render($this->render("mustache/account-row.phtml"), array(
            "id" => $this->account->id,
            "accountUrl" => $this->createUrl("account", $this->account),
            "name" => strtoupper($this->account->name),
            "benefit" => $this->currencyValue($this->account->benefit, $this->account->id_currency),
            "date_ini" => Contabilidad_Utils_Dates::toDate($this->account->date_ini),
            "date_end" => Contabilidad_Utils_Dates::toDate($this->account->date_end),
            "picture_url" => $this->account->getPictureUrl()
        ));?>
    <?=$this->count?> transacciones
    <p>Beneficio a la fecha: <?= $this->currentBenefit ?></p>
</div>
<a href="#" id="add-income" class="add-transaction" onclick="return false;">Adicionar ingresos</a>
<br>
<a href="#" id="add-expense" class="add-transaction" onclick="return false;">Adicionar egresos</a>
<?php if(count($this->outsideTrans)){?>
    <h3 id="outside-transactions-title"> transacciones por fuera del periodo</h3>
    <div id="outside-transactions-container">
        <a href="#" id="delete-outside-transactions"><?= $this->tr("Eliminar todas las transacciones") ?></a>
        <?php
        $m = new Mustache_Engine;
        foreach ($this->outsideTrans as $transaction){ 
        ?>
            <?= $m->render($this->render("mustache/transaction-row.phtml"), array(
                "id" => $transaction->id,
                "transactionUrl" => $this->createUrl("transaction", $transaction),
                "name" => $transaction->name,
                "timestampDate" => $transaction->date,
                "date" => Contabilidad_Utils_Dates::toDate($transaction->date),
                "value" => $this->currencyValue($transaction->value, $this->account->id_currency),
                "dateClass" => $transaction->date > time() ? "@" : "",
                "transactionType" => $transaction->id_transaction_type == 1 ? "income" : "expense"
            ));?>
        <?php }?>
    </div>
<?php }?>
<?php if(count($this->transactions)) { ?>
    <h3 id="transactions-title"><?= $this->tr("Transacciones") ?></h3>
<?php }?>
<div id="transactions-container">
    <?php
    $m = new Mustache_Engine;
    foreach ($this->transactions as $transaction){ 
    ?>
        <?= $m->render($this->render("mustache/transaction-row.phtml"), array(
            "id" => $transaction->id,
            "transactionUrl" => $this->createUrl("transaction", $transaction),
            "name" => $transaction->name,
            "timestampDate" => $transaction->date,
            "date" => Contabilidad_Utils_Dates::toDate($transaction->date),
            "value" => $this->currencyValue($transaction->value, $this->account->id_currency),
            "dateClass" => $transaction->date > time() ? "@" : "",
            "transactionType" => $transaction->id_transaction_type == 1 ? "income" : "expense"
        ));?>
    <?php }?>
</div>

<script type="text/html" id="transaction-row-tpl" class="template" style="display: none;">
    <?= $this->render("mustache/transaction-row.phtml") ?>
</script>

<script type="text/html" id="create-mini-transaction-tpl" style="display: none;">
    <?php echo $this->render('partials/createMiniTransactionForm.phtml'); ?>
    <div class="response"></div>
</script>

<script type="text/html" id="create-transaction-form" style="display: none;">
    <?php echo $this->render('partials/createTransactionForm.phtml'); ?>
    <div class="response"></div>
</script>

<script type="text/html" id="create-account-form" style="display: none;">
    <?php echo $this->render('partials/createAccountForm.phtml'); ?>
    <div class="response"></div>
</script>

<script language="javascript">
    window.Contabilidad.account = <?= Zend_Json::encode($this->serializedAccount); ?>;
    window.Contabilidad.transactions = <?= Zend_Json::encode($this->serializedTransactions); ?>;
</script>
