<script language="javascript">
    var BASE_URL = "<?= BASE_URL; ?>";
    var GOOGLE_API = "<?= $this->gapi_id; ?>";
    var GOOGLE_SECRET = "<?= $this->gapi_secret; ?>";
    
    window.Contabilidad = window.Contabilidad || {};
    window.Contabilidad.controller = "<?= $this->controller; ?>";
    window.Contabilidad.module = "<?= $this->module; ?>";
    window.Contabilidad.action = "<?= $this->action; ?>";
</script>
<link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/css/jquery-ui-1.9.2.custom.css"/>
<link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/css/jquery.qtip.css"/>
<script src="<?=BASE_URL?>/js/library/jquery-1.7.2.min.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/Mustache.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/jquery-ui-1.9.2.custom.min.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/jquery.qtip.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/json2.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/jquery.zend.jsonrpc.js" language="javascript" type="text/javascript"></script>
<script type="text/javascript" src="<?=BASE_URL?>/js/library/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?=BASE_URL?>/js/library/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/js/library/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script src="<?=BASE_URL?>/js/library/googleLogin.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/global.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/library/contabilidad/Validate.js" language="javascript" type="text/javascript"></script>
<script src="<?=BASE_URL?>/js/<?=$this->module?>/<?=$this->controller?>/<?=$this->action?>.js" language="javascript" type="text/javascript"></script>
<script id="google-api" src="https://apis.google.com/js/client.js?onload=OnLoadGApiCallback"></script>
<?= $this->headScript();?>