<script language="javascript">
    var BASE_URL = "<?= BASE_URL; ?>";
    var LINKS_URL = "<?= LINKS_URL; ?>";
    var GOOGLE_API = "<?= $this->gapi_id; ?>";
    var GOOGLE_SECRET = "<?= $this->gapi_secret; ?>";
    var ID_FB_API = "<?= $this->facebook_id; ?>";
    
    window.Contabilidad = window.Contabilidad || {};
    window.Contabilidad.controller = "<?= $this->controller; ?>";
    window.Contabilidad.module = "<?= $this->module; ?>";
    window.Contabilidad.action = "<?= $this->action; ?>";
</script>

 <title>Quantups es para ti</title>
<!--<title><?=$this->title?></title>-->
<!--Meta data-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
<meta name="robots" content="ALL" />
<meta name="description" content="Una forma sencilla, gratuita y segura de controlar tu presupuesto... Quantups es para ti." />
<meta name="keywords" content="economía del hogar, presupuesto del hogar, crear presupuestos, aplicación web, gestión de cuentas, control de gastos, quantups, quantaps, quantupps, quantups, quantapps" />  <!--        PENDIENTE-->
<!--/Meta data-->
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/jquery-ui-1.9.2.custom.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/jquery.qtip.css"/>

<!--Exnius Framework-->
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/global.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/colors.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/text.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/layout.css" media="screen, projection"/>
<!--<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/layout-mobile.css" media="hendheld, tv"/>     PENDIENTE-->   
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/layout-mobile.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/input.css"/>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/global/buttons.css"/>
<link rel="shortcut icon" href="<?= LINKS_URL ?>favicon.ico" />
<!--<meta name="viewport" content="width=100%; initial-scale=1; maximum-scale=1; minimum-scale=1; user-scalable=no;" />-->
<!--/Exnius Framework-->

<script src="<?= LINKS_URL ?>/js/library/jquery-1.7.2.min.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/Mustache.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/jquery-ui-1.9.2.custom.min.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/jquery.qtip.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/json2.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/jquery.zend.jsonrpc.js" language="javascript" type="text/javascript"></script>
<script type="text/javascript" src="<?= LINKS_URL ?>/js/library/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?= LINKS_URL ?>/js/library/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/js/library/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<?php if (!$this->isLogged) { ?>
    <script src="<?= LINKS_URL ?>/js/library/googleLogin.js" language="javascript" type="text/javascript"></script>
    <script src="<?= LINKS_URL ?>/js/library/facebookLogin.js" language="javascript" type="text/javascript"></script>
<?php } else { ?>
    <script src="<?= LINKS_URL ?>/js/private/helpers/account.js" language="javascript" type="text/javascript"></script>
<?php } ?>
<script src="<?= LINKS_URL ?>/js/global.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/library/contabilidad/Validate.js" language="javascript" type="text/javascript"></script>
<script src="<?= LINKS_URL ?>/js/<?= $this->module ?>/<?= $this->controller ?>/<?= $this->action ?>.js" language="javascript" type="text/javascript"></script>
<?php if (!$this->isLogged) { ?>
    <script id="google-api" src="https://apis.google.com/js/client.js?onload=OnLoadGApiCallback"></script>
<?php } ?>
<?= $this->headScript(); ?>