<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd"> 
    <?php $login = array("action" => "login", "controller" => "session", "module" => "public") ?>

<html>
    <head>
        <?php echo $this->render('headLinks.phtml'); ?>
        <link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/public/index.css"/>
        
    </head>

    <body class="public">
        <div id="fb-root"></div>

        <a href="#" onclick="window.open('https://twitter.com/intent/tweet?&text=Ahora%20uso%20%23Quantups%20y%20puedo%20controlar%20super%20fácil%20mi%20dinero.%20Entra%20a%20www.quantups.com%20y%20síguelos%20en%20%40Quantups', 'Twitter', 'device-width=10', 'height=5', 'status=no', 'scrollbars=no', 'toolbars=no', 'menubar=no', 'direction=no', 'location=no'); return false;">
            <img src="<?= LINKS_URL ?>/images/buttons/twit-gift.png" id="button-twit-gift" class="fixed-bar transition-3s opacity-95-percent opacity-on-hover-no-opacity bg-color-transparent"/>
        </a>
        <?= $this->layout()->content; ?>
    </body>
</html>