<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd"> 
    <?php $login = array("action" => "login", "controller" => "session", "module" => "public") ?>

<html>
    <head>
        <?php echo $this->render('headLinks.phtml'); ?>
        <link rel="stylesheet" type="text/css" href="<?= LINKS_URL ?>/css/public/index.css"/>
    </head>

    <body class="public">
        <div id="fb-root"></div>

        <a href="#" onclick="window.open('https://twitter.com/intent/tweet?&text=Ahora%20uso%20%23Quantups%20y%20puedo%20controlar%20super%20fácil%20mi%20dinero.%20Entra%20a%20www.quantups.com%20y%20síguelos%20en%20%40Quantups', 'Twitter', 'device-width=10', 'height=5', 'status=no', 'scrollbars=no', 'toolbars=no', 'menubar=no', 'direction=no', 'location=no'); return false;">
            <img src="<?= LINKS_URL ?>/images/buttons/twit-gift.png" id="button-twit-gift" class="fixed-bar transition-3s opacity-95-percent opacity-on-hover-no-opacity bg-color-transparent"/>
        </a>
        <?= $this->layout()->content; ?>



        <div id="bottom-container" class="">
            <ol id="social-media-icons-container" class="">
                <a href="<?= BASE_URL ?>/index/blog">
                    <li>
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/blog.png" title="<?= $this->tr("Blog") ?>"/>
                </a>
                </li>
                <li>
                    <a href="http://www.facebook.com/Quantups" target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/facebook.png" title="<?= $this->tr("Síguenos en Facebook") ?>"/>
                    </a>
                </li>
                <li>
                    <a href="http://www.twitter.com/Quantups" target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/twitter.png" title="<?= $this->tr("Síguenos en Twitter") ?>"/>
                    </a>
                </li>
                <li>
                    <a href="http://www.youtube.com/Quantups" target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/youtube.png" title="<?= $this->tr("Canal de Youtube") ?>"/>
                    </a>
                </li>

                <li>
                    <a href="http://www.facebook.com/sharer.php?u=http://quantups.com/" target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/facebook-2.png" title="<?= $this->tr("Compartir en Facebook") ?>"/>
                    </a>
                </li>
                <li>
                    <a href="https://www.delicious.com/save?url=<?= BASE_URL ?>&title=Quantups%3A%20La%20forma%20sencilla,%20gratuita%20y%20segura%20de%20controlar%20tu%20presupuesto." target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/delicious.png" title="<?= $this->tr("Agregar a Delicious") ?>"/>
                    </a>
                </li>
                <li>
                    <a href="http://www.linkedin.com/shareArticle?mini=true&url=http%3A//quantups.com&title=Quantups&summary=La%20forma%20sencilla,%20gratuita%20y%20segura%20de%20controlar%20tu%20presupuesto." target="_blank">
                        <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                             src="<?= LINKS_URL ?>/images/social-icons/linkedin.png" title="<?= $this->tr("Compartir en LinkedIn") ?>"/>
                    </a>
                </li>
            </ol>
            <ol class="bottom-text-container color-white bg-color-transparent">
                <li>
                    <a href="<?= BASE_URL ?>/index/about" class="color-white bg-color-transparent"><?= $this->tr("Acerca de nosotros") ?></a>
                </li>
                <li>
                    <a href="<?= BASE_URL ?>/index/terms"  class="color-white bg-color-transparent"><?= $this->tr("Términos y condiciones") ?></a>
                </li>
                <li>
                    <a href="<?= BASE_URL ?>/index/join" class="color-white bg-color-transparent"><?= $this->tr("Trabaja con nosotros") ?></a>
                </li>
                <li id="copyright" class="color-white bg-color-transparent">
                    © Quantups 2013
                </li>
            </ol>
        </div>

        <!--::::::::::::::::::::::::::::::::::::::::
               L O G I N             
        :::::::::::::::::::::::::::::::::::::::::-->
        <div id="login-form" style="display: none;">
            <?php echo $this->render('partials/loginForm.phtml'); ?>
            <div class="separation-transparent-10px"></div>
            <div id="loginForm" class="response"></div>
            <div class="separation-transparent-10px"></div>
        </div>
        <div id="register-form" style="display: none;">
            <div class="response"></div>
            <?php echo $this->render('partials/registerForm.phtml'); ?>
        </div>
        <div id="recover-password-form" style="display: none;">
            <div class="response"></div>
            <?php echo $this->render('partials/recoverPassForm.phtml'); ?>
            <div class="separation-transparent-10px"></div>
        </div>
    </body>
</html>