<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd"> 
<html>
<head>

    <title><?=$this->title?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
	<link rel="shortcut icon" href="<?=BASE_URL?>/assets/layouts/img/favicon.png" />
	
    <?php echo $this->render('headLinks.phtml'); ?>
	
</head>

<body class="wv-blank-layout">
    <?php if ($this->action != "home"){?><h1><a href="<?=BASE_URL?>">Private</a></h1> <?php }else{ ?>
    <h1>Private</h1> <?php } ?>
    <?php $logout = array("action" => "logout", "controller" => "session", "module" => "public"); ?>
    <?php $profile = array("action" => "index", "controller" => "profile", "module" => "private"); ?>
    <div>
        <a href="<?= $this->url($logout)?>">Logout</a>
    </div>
    <div>
        <a href="<?= $this->url($profile)?>"><?= $this->tr("Mi perfil")?></a>
    </div>
    <?= $this->layout()->content; ?>
    
    <div id="delete-popup-tpl" class="template" style="display: none;">
        <?= $this->render("mustache/delete.phtml") ?>
    </div>

</body>
</html>
