<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd"> 
<html>
<head>

    <title><?=$this->title?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
	<link rel="shortcut icon" href="<?=BASE_URL?>/assets/layouts/img/favicon.png" />
	
    <script language="javascript">
        var BASE_URL = "<?= BASE_URL; ?>";
    </script>

	<link rel="stylesheet" type="text/css" href="<?=BASE_URL?>/services/css"/>

	<script src="<?=BASE_URL?>/services/js" language="javascript" type="text/javascript"></script>
    <?= $this->headScript();?>
	
</head>

<body class="wv-blank-layout">
    <h1>Private</h1>
    <?= $this->layout()->content; ?>

</body>
</html>
