<form name="iform" action="<?= BASE_URL . "/uploadavatar"?>" method="post" enctype="multipart/form-data">
    <input id="file" type="file" name="avatar" onChange="window.parent.uploadAvatar(this);" /><br>
    <span><?= $this->tr("solo aceptamos archivos con extensiones gif, png, jpg.")?></span>
    <input type="hidden" value="" name="div_id" />
</form>

<script language="javascript">
    window.parent.addIframe(window);
</script>
