<a href="#"><?= $this->pru ?></a>


<div class="contenedor display-inline">
    <div class="separation-line-6px-dark-gray">Prueba de listado de presupuestos con info en hover</div>
    <div class="budget-summary">
        <div class="title" type="budget">
            <a href="#" class="color-gray-1">
                Presupuesto de febrero
            </a>
        </div><!--/budget-title-->

        <div class="image">
            <img src="<?= LINKS_URL ?>/images/slider/08.jpg"/>
            <div class="statistics">
                <p class="description">
                    140 caracteres que deben ocupar cinco o seis líneas... Itsit elit, sed ummy nibh euismo. Palabra superhípermegalargototota de 25 caracteres.
                </p>

                <ul class="chart">
                    <li><span style="height:20%" class="bg-color-green-1"></span></li> <!--Ingresos-->
                    <li><span style="height:80%" class="bg-color-red-1"></span></li> <!--Egresos-->
                    <!--as many more items as you want !-->
                </ul>
            </div><!--/budget-summary-statistics-->
        </div>
        <div class="period">
            10/11/2012&nbsp;&nbsp;•&nbsp;&nbsp;03/11/2013
        </div>




    </div><!--//END #home-heroImage-->
</div> 
