<a href="#"><?= $this->user->full_name ?></a></br>
<a id="js-fancy-create-account" href="#"><?= $this->tr("Crear contabilidad")?></a></br>

<div id="accounts-container">
    <?php $m = new Mustache_Engine;
    foreach ($this->accounts as $account){
    ?>
        <?= $m->render($this->render("mustache/account-row.phtml"), array(
            "id" => $account->id,
            "accountUrl" => $this->createUrl("account", $account),
            "name" => $account->name,
            "benefit" => $account->benefit,
            "date_ini" => Contabilidad_Utils_Dates::toDate($account->date_ini),
            "date_end" => Contabilidad_Utils_Dates::toDate($account->date_end)
        ));?>
    <?php }?>
</div>
<div id="account-row-tpl" class="template" style="display: none;">
    <?= $this->render("mustache/account-row.phtml") ?>
</div>

<div id="create-account-form" style="display: none;">
    <?php echo $this->render('partials/createAccountForm.phtml'); ?>
    <span class="js-time" style="display: none;"><?= time();?></span>
    <div class="response"></div>
</div>

<script language="javascript">
    window.Contabilidad.accounts = <?= Zend_Json::encode($this->serializedAccounts); ?>;
</script>