<a href="#"><?= $this->user->full_name ?></a></br>
<a id="js-fancy-crear-contabilidad" href="#"><?= $this->tr("Crear contabilidad")?></a></br>

<?php
    foreach ($this->accounts as $account){?>
<br><a href="<?= $this->createUrl("account", $account) ?>"><span class="js-account-name"><?= $account->name ?></span> </a> <br>Id de cuenta: <?= $account->id?> <br>Balance: <?= $account->benefit?><br><br>
<?php }?>

<div id="create-account-form" style="display: none;">
    <?php echo $this->render('partials/createAccountForm.phtml'); ?>
    <span class="js-time" style="display: none;"><?= time() ?></span>
    <div class="response"></div>
</div>