<div id="top-bar" class="">
    <a href="<?= BASE_URL ?>" title="Quantups">
        <img id="logo" class="bg-color-transparent" src="<?= LINKS_URL ?>/images/logo.png"/>
    </a>
    <div id="login-container-secondary" class="fade-in">
            <a href="#">
                <img id="google-login" class="login-button js-google-login" 
                     src="<?= LINKS_URL ?>/images/login/login-google.png" title="<?= $this->tr("Iniciar sesión con Google") ?>"/>
            </a>
            <a href="#">
                <img id="facebook-login" class="login-button js-facebook-login" 
                     src="<?= LINKS_URL ?>/images/login/login-facebook.png" title="<?= $this->tr("Iniciar sesión con Facebook") ?>"/>
            </a>
            <a href="#">
                <img id="mail-login" class="login-button js-fancy-login" 
                     src="<?= LINKS_URL ?>/images/login/login-mail.png" title="<?= $this->tr("Iniciar sesión con una cuenta de correo") ?>"/>
            </a>
    </div>
</div> <!--/top-bar-->