<div id="bottom-container-secondary" class="transition-3s">
    <div id="social-media-icons-container" class="">
        <a href="<?= BASE_URL ?>/index/blog">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/blog.png" title="<?= $this->tr("Blog") ?>"/>
        </a>
        <a href="http://www.facebook.com/Quantups" target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/facebook.png" title="<?= $this->tr("Síguenos en Facebook") ?>"/>
        </a>
        <a href="http://www.twitter.com/Quantups" target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/twitter.png" title="<?= $this->tr("Síguenos en Twitter") ?>"/>
        </a>
        <a href="http://www.youtube.com/Quantups" target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/youtube.png" title="<?= $this->tr("Canal de Youtube") ?>"/>
        </a>

        <a href="http://www.facebook.com/sharer.php?u=http://quantups.com/" target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/facebook-2.png" title="<?= $this->tr("Compartir en Facebook") ?>"/>
        </a>
        <a href="https://www.delicious.com/save?url=<?= BASE_URL ?>&title=Quantups%3A%20La%20forma%20sencilla,%20gratuita%20y%20segura%20de%20controlar%20tu%20presupuesto." target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/delicious.png" title="<?= $this->tr("Agregar a Delicious") ?>"/>
        </a>
        <a href="http://www.linkedin.com/shareArticle?mini=true&url=http%3A//quantups.com&title=Quantups&summary=La%20forma%20sencilla,%20gratuita%20y%20segura%20de%20controlar%20tu%20presupuesto." target="_blank">
            <img class="social-media-icon opacity-50-percent opacity-on-hover-no-opacity bg-color-transparent" 
                 src="<?= LINKS_URL ?>/images/social-icons/linkedin.png" title="<?= $this->tr("Compartir en LinkedIn") ?>"/>
        </a>
    </div>
    <div class="bottom-text-container white-space-pre-line color-white bg-color-transparent">
        <a href="<?= BASE_URL ?>/index/about" class="color-white bg-color-transparent"><?= $this->tr("Acerca de nosotros") ?></a>
        <a href="<?= BASE_URL ?>/index/terms"  class="color-white bg-color-transparent"><?= $this->tr("Términos y condiciones") ?></a>
        <a href="<?= BASE_URL ?>/index/join" class="color-white bg-color-transparent"><?= $this->tr("Trabaja con nosotros") ?></a>
    </div>
    <div id="copyright" class="bottom-text-container color-white bg-color-transparent">© Quantups 2013</div>
</div>