<?php $login = array("action" => "login", "controller" => "session", "module" => "public")?> 
<a class="js-google-login" href="#"><?= $this->tr("Entrar por google")?></a>
<form action="<?= $this->url($login); ?>" method="POST">
    <h1>login</h1>
    <p>Email</p>
    <input type="text" name="email" class="required is_email">
    <p>Contraseña</p>
    <input type="password" name="password" class="required">
    <input type="submit" value="Login" />  
 </form>
<a id="js-fancy-recover-password" href="#"><?= $this->tr("¿Olvidaste la contraseña?")?></a>