<div id="register" class="text-align-center border-radius-0 color-gray-1 form-box padding-20px">
    <h3 class="color-gray-1"><?= $this->tr("Regístrate con tu cuenta de correo") ?></h3>
    <h6>-</h6> <!--Separador-->
    <div class="QapTcha"></div>
    <h6>-</h6> <!--Separador-->
    <form action="" method="POST" class="bg-color-transparent color-gray-1">
        <input
            id="input-name" 
            type="text" 
            name="full_name" 
            class="required input-text" 
            placeholder="<?= $this->tr("Nombre completo") ?>"
            >
        <h6>-</h6> <!--Separador-->

        <input 
            id="input-email" 
            type="text" 
            name="email" 
            class="required is_email input-text" 
            placeholder="<?= $this->tr("Correo electrónico") ?>"
            > 

        <h6>-</h6> <!--Separador-->

        <input 
            type="password" 
            name="password" 
            class="input-password required input-text" 
            placeholder="<?= $this->tr("Contraseña") ?>"
            >

        <h6>-</h6> <!--Separador-->

        <input 
            type="password" 
            name="confirm_password" 
            class="input-password required input-text" 
            is_equal_to="password" 
            placeholder="<?= $this->tr("Contraseña (nuevamente)") ?>"
            />

        <h6>-</h6> <!--Separador-->

        <input 
            class="input-button"
            type="submit" 
            value="<?= $this->tr("Registrar") ?>" 
            />
    </form>
    <h6>-</h6> <!--Separador-->
    <p id="info" class="padding-0 margin-left-right-auto color-gray-1">
        <?= $this->tr("Para mayor comodidad, puedes registrarte rápidamente usando una cuenta de") ?>
        <a 
            id="google-login"
            class="js-google-login" 
            href="#">Google</a>
        <?= $this->tr("o una de") ?> 
        <a 
            id="facebook-login"
            class="js-facebook-login" 
            href="#">
            Facebook
        </a>.

        <!--PENDIENTE: Alinear el validador-->
    </p>
</div>