<a href="#"><?= $this-> pru ?></a>
    
<h1>Menu Editar Perfil</h1>
    

<form action="http://micontabilidad.com/private/user/uploadpicture" method="post" enctype="multipart/form-data"> 
    Archivo: <input name="fichero" type="file"> 
    <input name="submit" type="submit" value="Upload!">  
</form>
    <form action="  ">
       
        <br>
        
        Mi nombre...<br>
        <input value="<?= $this->user->full_name?>" type="text" name="full_name"><br>
        Mi Ubicacion...<br>
        <input value="<?= $this->user->city?>" type="text" name="city"><br>
        Pais
        <select name="contry">
            <option selected><?= $this->user->country?></option>
            <option></option>
        </select>
        Tipo de Moneda
        <select name="id_currency">
            <?php foreach ($this->currencys as $currency){?>
                <?php if($currency->id == $this->user->id_currency) {?>
                    <option value="<?= $currency->id?>" selected=""><?= $currency->name ?></option>
                <?php }else {?>
                    <option value="<?= $currency->id?>"><?= $currency->name ?></option>
                <?php }?>
             <?php }?>
            
        </select>
        <br>
        <input type="button" value="Guardar">
        <input type="button" value="Borrar">
            
    </form>