<?php echo $this->render('partials/anotherTop.phtml'); ?>
<div id="wrapper" class="fade-in">
    <div class="bg-color-transparency-3 border-color-gray-3 border-style-solid border-width-1px margin-left-right-auto border-radius-10px">

        <h2 class="text-align-center font-size-190-percent color-white">
            <?= $this->tr("El equipo Quantups") ?>
        </h2> 
        <div class="text-align-center">
            <img src="<?= LINKS_URL ?>/images/team/team.jpg" 
                 class="width-75-percent margin-top-25px margin-bottom-10px border-radius-15px"/>
        </div> 

        <div class="position-float-clear-both separation-transparent-20px"></div>
        <div class="position-float-clear-both separation-transparent-20px"></div>
        <div id="team">
            <div id="andres" class="team-member">
                <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                <div class="position-float-clear-both separation-transparent-20px"></div>
                <div class="font-bold font-size-130-percent color-gray-1">
                    Andres Peña Carmona
                </div> 
                <p class="color-gray-1">
                    <?= $this->tr("Director de proyecto.") ?>
                </p>
                <p>
                    <a href="#" target="_blank" class="color-gray-1">Portafolio</a>
                </p>
            </div>

            <div id="helman" class="team-member">
                <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                <div class="position-float-clear-both separation-transparent-20px"></div>
                <div class="font-bold font-size-130-percent color-gray-1">
                    Helman Rodríguez
                </div> 
                <p class="color-gray-1">
                    <?= $this->tr("Desarrollador") ?>
                </p>
                <p>
                    <a href="#" target="_blank" class="color-gray-1">Portafolio</a>
                </p>
            </div>

            <div id="exnius" class="team-member">
                <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                <div class="position-float-clear-both separation-transparent-20px"></div>
                <div class="font-bold font-size-130-percent color-gray-1">
                    Exnius
                </div> 
                <p class="color-gray-1">
                    <?= $this->tr("Diseñador de interfaz.") ?>
                </p>
                <p>
                    <a href="#" target="_blank" class="color-gray-1">Portafolio</a>
                </p>
            </div>

            <div class="position-float-clear-both separation-transparent-20px"></div>
        </div>
    </div>
</div>