<?php echo $this->render('partials/anotherTop.phtml'); ?>
<div id="wrapper" class="fade-in">
    <article class="bg-color-transparency-3 margin-left-right-auto padding-10px">

        <h1 class="text-align-center font-size-190-percent color-white">
            <?= $this->tr("El equipo Quantups") ?>
        </h1> 

        <!--Team photo-->
        <figure class="text-align-center">
            <img src="<?= LINKS_URL ?>/images/team/team.jpg" 
                 class="width-75-percent margin-top-25px margin-bottom-10px border-radius-5px"/>
        </figure> 
        <div class="separation-transparent-30px"></div>

        <!--Team members-->
        <ol id="team">
            <li id="andres" class="team-member">
                <figure>
                    <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                </figure>
                <h3>
                    Andres Peña Carmona
                </h3> 
                <p>
                    <?= $this->tr("Dirección de proyecto y desarrollo web.") ?>
                </p>
                <p>
                    <a href="https://twitter.com/andrewsxx" target="_blank">@andrewsxx</a>
                </p>
            </li>
            <li id="helman" class="team-member">
                <figure>
                    <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                </figure>
                <h3>
                     Helman Rodríguez
                </h3> 
                <p>
                    <?= $this->tr("Desarrollo web y base de datos.") ?>
                </p>
                <p>
                    <a href="https://twitter.com/HelmanRL" target="_blank">@HelmanRL</a>
                </p>
            </li>

            <li id="exnius" class="team-member">
                <figure>
                    <img src="<?= LINKS_URL ?>/images/team/team-1.png"/>
                </figure>
                <h3>
                     Fernando Caicedo Albarello
                </h3> 
                <p>
                    <?= $this->tr("Diseño de interfaz y de experiencia de usuario.") ?>
                </p>
                <p>
                    <a href="https://twitter.com/exniu" target="_blank">@exnius</a>
                </p>
            </li>
        </ol>
        <div class="position-float-clear-both separation-transparent-20px"></div>
    </article>
</div>