<?php echo $this->render('partials/anotherTop.phtml'); ?>
<div id="wrapper" class="fade-in">
    <div id="blog" class="bg-color-transparency-3 border-color-gray-3 border-style-solid border-width-1px margin-left-right-auto border-radius-10px padding-left-right-20px">
        <div class="text-align-left margin-left-20px">
            <img src="<?= LINKS_URL ?>/images/blog/blog.png" 
                 class="margin-top-25px margin-bottom-10px border-radius-15px"/>
        </div> 
        <div class="separation-transparent-30px"></div>
        <div id="blog-updates" class="margin-left-right-auto padding-10px">
            <p class="font-size-110-percent color-white font-bold padding-top-bottom-10px margin-bottom-10px">
                <?= $this->tr("Mejoras recientes") ?>
            </p> 
            <p class="color-white font-size-90-percent">Unificación de la interfaz pública.</p>
            <p class="color-white font-size-90-percent">Compatibilidad con tabletas.</p>

        </div>
        <div class="separation-transparent-30px"></div>
        <p class="color-white">
            <?= $this->tr("¿Qué es la economía del hogar?") ?>
        </p> 
        <p class="color-white">
            <?= $this->tr("Para qué sirve un presupuesto familiar") ?>
        </p> 
        <p class="color-white">
            <?= $this->tr("Para qué sirve un presupuesto personal") ?>
        </p> 
        <p class="color-white">
            <?= $this->tr("Consejos para ahorrar") ?>
        </p> 
        <p class="color-white">
            <?= $this->tr("Consejos para ahorrar") ?>
        </p> 

        <p>
            <a href="http://www.wikilearning.com/apuntes/econimia_del_hogar-economia_en_el_hogar/9686-1" class="color-white" target="_blank"><?= $this->tr("Taller de economía del hogar (www.wikilearning.com)") ?></a>
        </p>
        <div class="separation-transparent-30px"></div>

    </div>
</div>

<!--PENDIENTE-->

<!--Ejemplo: http://blog.twitter.com/-->