<?php $register = array("action" => "register", "controller" => "session", "module" => "public") ?>
<?php $login = array("action" => "login", "controller" => "session", "module" => "public") ?>

<!--<a id='google-login' class="js-google-login" href="#"><?= $this->tr("Entrar por google") ?></a>-->
<!--<a id='facebook-login' class="js-facebook-login" href="#"><?= $this->tr("Entrar por facebook") ?></a>-->
<!--<a href="<?= $this->url($register) ?>" class="js-fancy-register"> Register</a>-->
<!--<a  href="<?= $this->url($login) ?>" class="js-fancy-login">Usa tu cuenta de correo</a>-->

<!--::::::::::::::::::::::::::::::::::::::::
               L O G I N             
:::::::::::::::::::::::::::::::::::::::::-->
<div id="login-form" style="display: none;">
    <?php echo $this->render('partials/loginForm.phtml'); ?>
    <div class="separation-transparent-10px"></div>
    <div id="loginForm" class="response"></div>
    <div class="separation-transparent-10px"></div>
</div>
<div id="register-form" style="display: none;">
    <div class="response"></div>
    <?php echo $this->render('partials/registerForm.phtml'); ?>
</div>
<div id="recover-password-form" style="display: none;">
    <div class="response"></div>
    <?php echo $this->render('partials/recoverPassForm.phtml'); ?>
    <div class="separation-transparent-10px"></div>
</div>

<!--::::::::::::::::::::::::::::::::::::::::
               TESTIMONIES
:::::::::::::::::::::::::::::::::::::::::-->
<div id="testimonies-container" class="">
    <div class="testimony">
        <img class="" src="<?= LINKS_URL ?>/images/testimonies/01.jpg"/>
        <p class="">
            Olvídate de las hojas de cálculo.
        </p>
    </div>
    <div class="testimony">
        <img class="" src="<?= LINKS_URL ?>/images/testimonies/02.jpg"/>
        <p class="">
            Desperdiciábamos mucho tiempo haciendo el presupuesto del mes, ahora tenemos más tiempo libre.
        </p>
    </div>
    <div class="testimony">
        <img class="" src="<?= LINKS_URL ?>/images/testimonies/03.jpg"/>
        <p class="">
            Quantups es muy fácil de usar. 
        </p>
    </div>
</div>

<!--::::::::::::::::::::::::::::::::::::::::
               EXTRA INFO
:::::::::::::::::::::::::::::::::::::::::-->

<!--<div id="extra-box-1" class="extra-box color-gray-1 border-color-blue-2 border-style-solid border-width-1px">
    Extra Box 1
</div>



<div class="extra-box position-float-clear-both">

    <h3><?= $this->tr("Texto opcional") ?></h3>
    <p class="color-gray-1"> 
<?= $this->tr("Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.") ?>
    </p> 
</div>
-->



