<?php $register = array("action" => "register", "controller" => "session", "module" => "public") ?>
<?php $login = array("action" => "login", "controller" => "session", "module" => "public") ?>

<!--<a id='google-login' class="js-google-login" href="#"><?= $this->tr("Entrar por google") ?></a>-->
<!--<a id='facebook-login' class="js-facebook-login" href="#"><?= $this->tr("Entrar por facebook") ?></a>-->
<!--<a href="<?= $this->url($register) ?>" class="js-fancy-register"> Register</a>-->
<!--<a  href="<?= $this->url($login) ?>" class="js-fancy-login">Usa tu cuenta de correo</a>-->


<div id="extra-box-1" class="margin-top-25px color-white-yellow border-color-blue-2 border-style-solid border-width-1px"><p>Extra Box example</p></div>
<div id="extra-box-2" class="margin-top-25px bg-color-gray-3 color-white-yellow border-color-blue-2 border-style-solid border-width-1px">Extra Box example</div>


<div id="login-form" style="display: none;">
    <?php echo $this->render('partials/loginForm.phtml'); ?>
    <div class="response"></div>
</div>

<div id="register-form" style="display: none;">
    <?php echo $this->render('partials/registerForm.phtml'); ?>
    <div class="response"></div>
</div>

<div id="recover-password-form" style="display: none;">
    <?php echo $this->render('partials/recoverPassForm.phtml'); ?>
    <div class="response"></div>
</div>