<?php $register = array("action" => "register", "controller" => "session", "module" => "public")?>
<?php $login = array("action" => "login", "controller" => "session", "module" => "public")?>

<table style="width: 100%;" border="2">
    <tr style="height: 200px;">
        <td>
            <table style="width: 100%; height: 180px;" border="1">
                <tr>
                    <td style="width: 80%;">LOGO</td>
                    <td>
                        <a href="<?= $this->url($register)?>" class="js-fancy-register"> Register</a>
                        <br/>
                        <a  href="<?= $this->url($login)?>" class="js-fancy-login"> Login</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table style="width: 100%; height: 400px;" border="1">
                <tr>
                    <td>HELP</td>
                </tr>
                <tr><td>TESTIMONIES</td></tr>
                <tr><td>FOOTER</td></tr>
            </table>
       </td>
    </tr>
</table>

<div id="login-form" style="display: none;">
    <?php echo $this->render('partials/loginForm.phtml'); ?>
    <span class="error"></span>
</div>

<div id="register-form" style="display: none;">
    <?php echo $this->render('partials/registerForm.phtml'); ?>
    <span class="error"></span>
</div>