<?php echo $this->render('partials/anotherTop.phtml'); ?>
<div id="wrapper" class="fade-in">
    <article id="main-container" 
         class="bg-color-transparency-3 margin-left-right-auto padding-10px">
        <h1 class="text-align-center font-size-190-percent color-white">
            <?= $this->tr("Términos y condiciones") ?>
        </h1> 
        <p class="color-white white-space-pre-line">
            <?= $this->tr("Términos
                -
                -
                -
                -
                -
                -
                -
                ") ?>
        </p> 
        <p class="font-size-110-percent color-white white-space-pre-line">
            <?= $this->tr("Condiciones
                -
                -
                -
                -
                -
                -
                -
                -
                -
                -
                ") ?>&nbsp;
        </p>

        <div class="separation-transparent-30px"></div>

    </article>
</div>
<!--PENDIENTE-->