<div id="main-container" class="bg-color-transparency-3 border-color-gray-3 border-style-solid border-width-1px margin-left-right-auto border-radius-10px padding-left-right-20px">
    <h2 class="text-align-center font-size-190-percent color-white">
        <?= $this->tr("Términos y condiciones") ?>
    </h2> 
    <p class="color-white white-space-pre-line">
        <?= $this->tr("Términos
            -
            -
            -
            -
            -
            -
            -
            ") ?>
    </p> 
    <p class="font-size-110-percent color-white white-space-pre-line">
        <?= $this->tr("Condiciones
            -
            -
            -
            -
            -
            -
            -
            -
            -
            -
            ") ?>&nbsp;
    </p>

    <div class="separation-transparent-30px"></div>

</div>



<!--PENDIENTE-->